name: NBTC NR Scraper (05:00 IST)

on:
  schedule:
    # 23:30 UTC == 05:00 IST
    - cron: "30 23 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: pip install -r scraper/requirements.txt

      - name: Load last known ID
        id: state
        run: |
          LAST=$(jq -r '.last_id // 1628277' state.json 2>/dev/null || echo 1628277)
          echo "last=$LAST" >> $GITHUB_OUTPUT

      - name: Run scraper
        id: scraper
        env:
          START_ID: ${{ steps.state.outputs.last }}
        run: |
          set -e
          python scraper/nbtc_scraper.py
          echo "devices=$(jq -rc . new_devices.json)" >> $GITHUB_OUTPUT

      - name: Commit updated files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add state.json new_devices.json
          git diff --cached --quiet || (git commit -m "update state & devices $(date -u +%F)" && git push)

      - name: Create GitHub Issue
        uses: actions/github-script@v7
        with:
          script: |
            const devices = ${{ steps.scraper.outputs.devices }};
            const body = devices.map(d =>
              `- **${d.brand} ${d.model}** (ID: ${d.id}, Cert: ${d.cert})`
            ).join('\n');
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `New NBTC 5G device – ${new Date().toISOString().slice(0,10)}`,
              body
            });
            
