name: MoCheck Daily Scraper
on:
  schedule:
    - cron: "30 23 * * *"   # 23:30 UTC == 05:00 IST
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: "3.11"}
      - run: pip install -r requirements.txt
      - run: python scraper.py
        id: scrape
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID:   ${{ secrets.CHAT_ID }}

      - name: Persist state files
        if: always()
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add .last_id known.json
          git diff --cached --quiet || git commit -m "Update state [skip ci]"
          git push
          
